version: '3.8'

services:
  ai-agent:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - GROQ_API_KEY=${GROQ_API_KEY}
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
    volumes:
      - ./.env:/app/.env
    restart: unless-stopped
    networks:
      - ai-agent-network

  # Optional: Redis for session management (if needed in the future)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped
  #   networks:
  #     - ai-agent-network

networks:
  ai-agent-network:
    driver: bridge